-- Production files generated by the BullMQ worker (one PNG per zone, 300 DPI).
-- These columns store the latest state for fast UI rendering on the admin
-- Designs and Orders pages.
ALTER TABLE "designs" ADD COLUMN "production_files" jsonb;--> statement-breakpoint
ALTER TABLE "designs" ADD COLUMN "production_status" varchar(20);--> statement-breakpoint
ALTER TABLE "designs" ADD COLUMN "production_error" text;
